---

- name: Install chocolatey
  win_chocolatey:
      name:
        - chocolatey
        - chocolatey-core.extension
      state: present

- name: Install multiple packages
  win_chocolatey:
    name:
    - 7zip
    - firefox
    - notepadplusplus
    - windirstat
    state: present